(function(g){var window=this;'use strict';var U3=function(a){a.qa("cardstatechange",a.Hk()&&a.Xo()?1:0)},V3=function(a,b){var c=g.$a(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Aib=function(a){var b=g.cs(a);
a=g.fs(a);return new g.Sr(b.x,b.y,a.width,a.height)},Bib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.KC(a,b,function(){g.LC(e);c.apply(a,arguments)},d)},Y3=function(a){a=g.gb(a);
delete W3[a];g.jd(W3)&&X3&&X3.stop()},Dib=function(){X3||(X3=new g.Bu(function(){Cib()},20));
var a=X3;a.isActive()||a.start()},Cib=function(){var a=g.kb();
g.Wc(W3,function(b){Eib(b,a)});
g.jd(W3)||Dib()},Z3=function(a,b,c,d){g.Vu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Eib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Fib(a,a.progress);1==a.progress?(a.j=0,Y3(a),a.onFinish(),a.vr()):a.isPlaying()&&a.rL()},Fib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Gib=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$3=function(a,b,c,d,e){Z3.call(this,b,c,d,e);
this.element=a},Hib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$3.call(this,a,b,c,d,e)},Iib=function(a){return Math.pow(a,3)},Jib=function(a){return 3*a*a-2*a*a*a},Kib=function(a){g.J.call(this);
this.B=a||window;this.j=[]},a4=function(a){return a.baseUrl||null},b4=function(a,b){return g.Zs(g.lr(a,b),function(c){return!!c})},Lib=function(a,b,c){function d(sa){var ma=sa.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var wa=f(ma.unsubscribedButtonText),ea=f(ma.subscribedButtonText);if(ma.subscribed){var za=f(ma.subscriberCountWithUnsubscribeText);var aa=f(ma.subscriberCountText)}else za=f(ma.subscriberCountText),aa=f(ma.subscriberCountWithSubscribeText);var Sa=null;if(sa.signinEndpoint){Sa=V3(sa,"signinEndpoint","webNavigationEndpointData","url");if(!Sa){var z,V;Sa=null==(V=g.T(null==(z=ma.signInEndpoint)?void 0:z.commandMetadata,g.L2))?void 0:
V.url}if(!Sa)return null}return wa&&(ea||Sa)?{subscribed:ma.subscribed,subscribeText:wa,subscribeCount:za,unsubscribeText:ea,unsubscribeCount:aa,enabled:ma.enabled,signinUrl:Sa,classic:sa.useClassicSubscribeButton}:null}
function e(sa){if(sa){var ma=[],wa=sa.videoId;wa&&ma.push("v="+wa);(wa=sa.playlistId)&&ma.push("list="+wa);(sa=sa.startTimeSeconds)&&ma.push("t="+sa);return"/watch?"+ma.join("&")}}
function f(sa){if(!sa)return null;var ma=sa.simpleText;return ma?ma:sa.runs?g.lr(sa.runs,function(wa){return wa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,x=!1,B=null,F=null,G=null,H=null,O=null,Q=null;if("VIDEO"===h)g.T(l,g.vG)?m=g.T(l,g.vG).url:(Q=g.T(l,g.oT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.T(l,g.vG)?m=g.T(l,g.vG).url:(Q=g.T(l,g.oT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=V3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=V3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=V3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V3(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,
ia="";if(b.metadata){var na=f(b.metadata);na&&(ia=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ia,callToAction:f(b.callToAction),LV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,aE:p,playlistLength:t,channelId:u,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,n7:n,sessionData:X?{itct:X}:null,Eba:q,AC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:b4(b.impressionUrls||[],a4),b7:b4(b.hovercardShowUrls||[],a4),clickUrls:b4(l.loggingUrls||[],a4),visualElement:g.BF(b.trackingParams),productPrice:H,additionalFeesText:O,watchEndpoint:Q||null}},Mib=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:b4(a.impressionUrls||[],a4),elements:b4(a.elements||[],function(d,e){return Lib(b,d,e)})};
a.trackingParams&&(c.visualElement=g.BF(a.trackingParams));return c},Nib=function(a){g.xV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.fS(a)||g.hS(a);this.events=new g.OK(this);g.L(this,this.events);this.events.T(this.player,g.dK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.eK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Ib);this.events.T(window,"focus",this.R$);this.load();var b=g.mf("STYLE");(g.We("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Oib=function(a){return a.player.getVideoData().Nd?"current":a.Z?"new":"current"},c4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Pib=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Mib(f,Oib(a))));d4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Zx;d&&(c.postParams={ad_tracking:d});if(b=g.FRa(b))if(b=g.In(b),b=g.Zd(b))a.C=g.bC(b,c)},d4=function(a,b,c){c=void 0===c?!0:c;
a.player.hf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Qib(a);c=[];d=new g.cK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.sU(a.player,a.B.element,4),a.D=new g.IG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Rib(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.sU(a.player,f.element,4);var h=new g.cK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Sib(a,f,e)}else g.HF(new g.aD("buildEndscreenElement null",
e))}a.player.uf(c);a.Ib()}},Qib=function(a){var b=g.CF(),c=g.DF();
c&&b&&a.endscreen.visualElement&&g.KB(g.NF)(void 0,c,b,a.endscreen.visualElement)},Rib=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:b.aE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.$u(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)}]};c=new g.U(c);var d=g.Xe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ju(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.iW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Tib(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.$u(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.Ju(c.element,"ytp-ce-placeholder");return c},e4=function(a){if(a.LV)var b=a.LV.thumbnails;
return Tib(b?b[b.length-1].url:null)},Tib=function(a){return a?{style:"background-image: url("+a+")"}:{}},Sib=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Ju(b.element,"ytp-ce-force-expand"),g4(a,c.id,!0)):(g.Lu(b.element,"ytp-ce-force-expand"),g.Lu(b.element,"ytp-ce-element-hover"),g4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Uib(a,b,c)});
b.Ta("mouseleave",function(){Vib(a,b,c)});
a.player.U().B||b.Ta("click",function(){g.Ju(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Wib(a,c,m)});
b.Ta("keypress",function(m){Wib(a,c,m)});
b.Ta("focus",function(){Uib(a,b,c)});
b.Ta("blur",function(){Vib(a,b,c)});
b.Ta("touchstart",function(){Uib(a,b,c)});
var l=g.Ze("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Lu(b.element,"ytp-ce-element-hover");g.Lu(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Ze("ytp-sb-subscribe",b.element));d(g.Ze("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Wib=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Iu(d,"ytp-ce-element");){g.Iu(d,"subscribe-label")&&Xib(a,b);
if(g.Iu(d,"ytp-ce-channel-subscribe"))return;d=g.yf(d)}if(!d||g.Iu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Vib(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Eba)Xib(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.In(f4(a,b.targetUrl)),g.iH(g.Zd(c),void 0,b.sessionData);else{var e=g.rS(a.player.U())||a.player.getVideoData().Nd,f=function(){var h=f4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.PB(h);e&&n&&(n.v||
n.list)?a.player.Do(n.v,l,n.list,!1,void 0,m||void 0):g.swa(h,l)};
Xib(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},f4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.yS(a)+b}else return"";return b},Uib=function(a,b,c){g.Iu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Ju(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Bu(function(){g.Ju(b.element,"ytp-ce-element-hover")},200)).start():g.Ju(b.element,"ytp-ce-element-hover"),h4(a,c.b7),g4(a,c.id,!0))},Vib=function(a,b,c){g.Lu(b.element,"ytp-ce-element-hover");
g.Lu(b.element,"ytp-ce-force-expand");g4(a,c.id,!1)},g4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Nu(a.j[e].element,"ytp-ce-element-shadow-show",c)},h4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||c4(a))c&&c();else{b=Yib(a,b);var e=0,f=!1,h=new g.Bu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.uE(b[a],d)}},Xib=function(a,b,c){h4(a,b.clickUrls,c);
(a=g.DF())&&b.n7&&g.UF(a,b.visualElement)},Yib=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Zib(b[d],c));return a},Zib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},$ib=function(a){return"string"===typeof a?a:""},i4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},ajb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},j4=function(a){return a.value?a.value:null},k4=function(a){if(!a)return null;
var b=g.In($ib(a.value));b=g.Zd(b);if(!b)return null;var c=i4(a.target,bjb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new ajb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},cjb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},fjb=function(a){if(!a)return null;
var b=i4(a.type,djb),c=i4(a.trigger,ejb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=k4(a?a:null);return b?new cjb(b,c,a):null},gjb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},hjb=function(a,b){return g.Cb(a.action,b)},ijb=function(a,b){this.context=a;
this.j=b},jjb=function(a){return a.customMessage?l4("div","iv-card-message",a.customMessage):""},m4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},kjb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(l4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},l4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.$u(c);return{I:a,W:b,xa:c}},ljb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.KC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.KC+");");c.dir=g.$u(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},n4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Zi.click,5)}},mjb=function(a,b){this.merchant=a;
this.price=b},njb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ojb=function(a,b){return b?b:njb(a)?"current":"new"},o4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Ya=new Map;this.bb=new Map;this.context.J.addEventListener(g.dK("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.eK("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},p4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.sL(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.rb=!1});
a.context.j.Ta(b,"touchmove",function(){a.rb=!0})},pjb=function(a){var b;
return(null==(b=g.T(a,g.vG))?0:b.url)?g.T(a,g.vG).url:(a=g.T(a,g.oT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},q4=function(a,b,c){return{jX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
H_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
MK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},qjb=function(a,b,c){o4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Na=this.Pb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.Ka=this.G=this.Va=this.j=null;this.ma=[];this.ra=this.N=this.If=this.Da=null;this.K=0;this.Fa=new g.Bu(function(){},c.X.Gi?4E3:3E3);
g.L(this,this.Fa);this.ob=new g.Bu(function(){});
g.L(this,this.ob);this.Aa=new ijb(c,function(e,f,h,l,m,n){p4(d,e,f,h,l,m,n)});
this.Y=new g.U({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.gb=new g.IG(this.Y,330);g.L(this,this.gb);this.Gb=g.Ze("iv-drawer-header-text",this.D);this.B=g.Ze("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Pb&&r4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Pb=d.C)&&s4(d)});
this.Sa=new g.OK(this);g.L(this,this.Sa);this.J.addEventListener("videodatachange",this.ut.bind(this))},rjb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){r4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){s4(a)});
var c=b.headerText;g.Af(a.Gb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.BF(b.trackingParams);a.N=g.BF(b.closeTrackingParams);a.If=g.BF(b.iconTrackingParams)},sjb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.jG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Zi:{},Yo:null,Gj:e.trackingParams?g.BF(e.trackingParams):null,If:f&&f.trackingParams?g.BF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
KC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};t4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.jG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:u4(a,c,b,f),sponsored:!1,Zi:q4(f,e,f.command),Yo:f.trackingParams?g.BF(f.trackingParams):null,Gj:e.trackingParams?g.BF(e.trackingParams):null,If:l&&l.trackingParams?g.BF(l.trackingParams):null,imageUrl:v4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.jG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,KC:null,title:f.title?g.jG(f.title):"",customMessage:f.callToAction?g.jG(f.callToAction):"",url:g.T(f.command,g.vG).url?k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(f.command,g.vG).url}):null,onClickCommand:null};t4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.jG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,Zi:q4(e,f,e.endpoint),Yo:e.trackingParams?g.BF(e.trackingParams):null,Gj:f.trackingParams?g.BF(f.trackingParams):null,If:l&&l.trackingParams?g.BF(l.trackingParams):null,channelId:g.T(e.endpoint,g.NU).browseId,customMessage:e.customText?g.jG(e.customText):null,EZ:v4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.jG(e.channelName):"",metaInfo:[e.subscriberCountText?g.jG(e.subscriberCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(e.endpoint,g.NU).canonicalBaseUrl?g.T(e.endpoint,g.NU).canonicalBaseUrl:"/channel/"+g.T(e.endpoint,g.NU).browseId}),onClickCommand:null};t4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.jG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,Zi:q4(e,f,e.action),Yo:e.trackingParams?g.BF(e.trackingParams):null,Gj:f.trackingParams?g.BF(f.trackingParams):null,If:l&&l.trackingParams?g.BF(l.trackingParams):null,TF:v4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.jG(e.customMessage):null,playlistVideoCount:g.jG(e.playlistVideoCount),title:e.playlistTitle?g.jG(e.playlistTitle):"",metaInfo:[e.channelName?g.jG(e.channelName):
"",e.videoCountText?g.jG(e.videoCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:pjb(e.action)}),onClickCommand:null};t4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.jG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,Zi:q4(e,f,e.action),Yo:e.trackingParams?g.BF(e.trackingParams):null,Gj:f.trackingParams?g.BF(f.trackingParams):null,If:l&&l.trackingParams?g.BF(l.trackingParams):null,TF:v4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.jG(e.lengthString):null,customMessage:e.customMessage?g.jG(e.customMessage):null,title:e.videoTitle?g.jG(e.videoTitle):"",metaInfo:[e.channelName?g.jG(e.channelName):
"",e.viewCountText?g.jG(e.viewCountText):""],isLiveNow:!!e.badge,url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:pjb(e.action)}),onClickCommand:null};t4(a,b)}}}}}a.K++},v4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},u4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},ujb=function(a,b){if(b=tjb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.fg.id),g.rf(b.QM),g.Hb(a.cards,b),a.SG(),w4(a)},r4=function(a,b,c){if(!a.C){a.gb.show();
a.Va=new g.Bu(function(){g.Ju(a.context.J.getRootNode(),g.XY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.DF();d&&a.Da&&a.N&&g.SF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.XX||(f.XX=!0,vjb(a.context.logger,f.fg.Zi.jX,b)),d&&g.SF(d,[f.fg.Yo]);U3(a.J);c&&(a.G=new g.Bu(function(){a.Ka=a.Z;a.tb.focus()},330),a.G.start())}},s4=function(a){a.C&&(a.gb.hide(),g.QC(a.Sa),g.Lu(a.context.J.getRootNode(),g.XY.IV_DRAWER_OPEN),a.C=!1,U3(a.J),a.G&&a.G.stop(),a.G=new g.Bu(function(){a.Ka&&(a.Ka.focus(),a.Ka=null)},330),a.G.start())},xjb=function(a){g.Ku(a.Ab(),
[g.XY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.sU(a.J,a.D,5);wjb(a);a.Z=g.Ze("ytp-cards-button",a.J.getRootNode());a.tb=g.Ze("iv-drawer-close-button",a.D);a.isInitialized=!0},wjb=function(a){var b=g.Ze("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.T4,a);a.context.j.Ta(a.B,"touchend",function(){a.Fa.start()});
a.context.j.Ta(a.B,"scroll",a.p5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Iu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.IE("iv-button-shown",a.F7,a));a.ma.push(g.IE("iv-button-hidden",a.E7,a));yjb(a)},yjb=function(a){a.ma.push(g.IE("iv-teaser-shown",a.F1,a));
a.ma.push(g.IE("iv-teaser-hidden",a.G7,a));a.ma.push(g.IE("iv-teaser-clicked",a.E1,a));a.Db=!0},zjb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.T(b.onClickCommand,g.dfb))?void 0:c.targetId)?(a.ra=b,!0):!1},Ajb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.dQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.T(h[0],g.yYa))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},t4=function(a,b){if(!zjb(a,b)||Ajb(a,b)){var c=Bjb(a,b);
if(c){var d={fg:b,QM:c.element,XX:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||yjb(a),ujb(a,b.id),c=Cjb(a,d),g.Sb(a.cards,c,0,d));else{a.isInitialized||xjb(a);ujb(a,b.id);var e=Cjb(a,d);g.Sb(a.cards,e,0,d);c.Ea(a.B,e);a.SG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,w4(a),Djb(a,d),r4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Ejb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Ejb(a,
d)}),w4(a))}}},Bjb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=ljb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?j4(b.url)||"":""},V:[m4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[l4("h2",void 0,b.title),d]}]}]};c=new g.U(c);n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:j4(b.url)||"","data-ytid":b.channelId},V:[m4(b.EZ),{I:"div",
S:"iv-card-content",V:[jjb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},kjb(b)]}]}]};c=new g.U(c);n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:j4(b.url)||""},V:[m4(b.TF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[jjb(b),l4("h2","iv-card-primary-link",b.title),kjb(b)]}]}]};c=new g.U(c);
n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=ljb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?j4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[l4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.mf("span");g.Af(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.ge(d,"adInfo");n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:j4(c))||""},V:[m4(b.TF,d),{I:"div",S:"iv-card-content",V:[jjb(b),l4("h2","iv-card-primary-link",b.title),kjb(b),f]}]}]};c=new g.U(e);n4(a,g.Ye("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Cjb=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.fg.startMs>c.fg.startMs||b.fg.startMs===c.fg.startMs&&b.fg.timestamp>=c.fg.timestamp?!0:!1});
return-1===a?0:a+1},Fjb=function(a){if(a.j)return"productListing"===a.j.fg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.mr(a.cards,function(c){return"productListing"===c.fg.type})}return g.mr(a.cards,function(c){return"productListing"===c.fg.type})},w4=function(a){g.Nu(a.J.getRootNode(),"ytp-cards-shopping-active",Fjb(a))},Ejb=function(a,b){if(!g.Iu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.DF(),d=a.j?a.j.fg.If:a.If;
c&&d&&g.TF(c,[d]);a.j=b;w4(a)}(c=a.isInitialized&&"none"==a.Ab().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.fg.teaserDurationMs&&a.J.nB(!0,{teaserText:b.fg.teaserText,durationMs:b.fg.teaserDurationMs,onClickCommand:b.fg.onClickCommand});a.ob.isActive()||((!a.C||!a.Fa.isActive()&&a.Na)&&Djb(a,b),a.ob.start(910+b.fg.teaserDurationMs))}},Djb=function(a,b){a.Y.Cb?(b=new Z3([0,
a.B.scrollTop],[0,b.QM.offsetTop],600,Jib),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.fG(a.Y,!0),a.B.scrollTop=b.QM.offsetTop,g.fG(a.Y,!1))},x4=function(a){return a.j&&a.j.fg?a.j.fg:a.cards[0]&&a.cards[0].fg?a.cards[0].fg:null},tjb=function(a,b){return g.Cb(a.cards,function(c){return c.fg.id===b})},y4=function(a,b,c){o4.call(this,a,b);
this.annotation=c;this.isActive=!1},Gjb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z4=function(a,b,c){y4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Hjb=function(a,b){var c=void 0===c?0:c;
var d=Aib(b).width;g.as(b,d);c=new Hib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Iib);g.L(a,c);a.context.C.Ta(c,"begin",function(){g.gs(b,!0)});
c.play()},Kjb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.iW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ea(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.gs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Vr(l,"right",b.image_width+"px");g.of(a.Ab(),l);a.C=new g.Bu(function(){Ijb(a,h,l)},500);
g.L(a,a.C);a.context.j.Ta(a.Ab(),"mouseover",function(){Jjb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Ab(),"mouseout",function(){a.C.start()})}},Jjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.fs(b);a.j||(b.style.width=g.$r(f.width,!0),c.style.width=g.$r(f.width,!0));g.Vr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Vr(d,"right","1px");a.D=!0;g.gs(b,!0);a.G=new g.Bu(function(){g.Ju(this.Ab(),"iv-branding-active")},0,a);
a.G.start()}},Ijb=function(a,b,c){g.Lu(a.Ab(),"iv-branding-active");
a.K=new g.Bu(function(){g.gs(b,!1);a.j||(c.style.width=g.$r(0,!0))},250);
a.K.start();a.D=!1},Ljb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Mjb=function(a,b,c){y4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Bu(function(){d.j.setAttribute("aria-hidden","true");g.gs(d.C,!1);g.gs(d.B,!0)},700,this);
g.L(this,this.G)},Pjb=function(a,b,c){c.stopPropagation();
Njb(a);Ojb(a,b);a.j.focus()},Qjb=function(a){a.isCollapsed||a.Z||a.D||(g.Ju(a.Ab(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Njb=function(a){a.G.stop();
a.isCollapsed&&(g.Mu(a.Ab(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.gs(a.B,!1),g.gs(a.C,!0))},Ojb=function(a,b){a.D||(a.D=g.ng(function(){Rjb(this);
Qjb(this)},b,a))},Rjb=function(a){a.D&&(g.Ua.clearTimeout(a.D),a.D=null)},Sjb=function(a){this.J=a},vjb=function(a,b,c){b&&(c?A4(a,b.map(function(d){return g.pu(d,c)})):A4(a,b))},A4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.uE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Tjb=function(a){g.xV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Sjb(this.player);this.D=new g.OK(this);this.G=this.xx=null;this.events=new g.OK(this);this.Wg=this.Z=this.j=null;this.ma=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.qa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.qa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.qa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.qa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.qa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.G1,this);this.subscribe("resize",this.wJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.iZ,this);g.L(this,this.events);this.ra=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.sU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.ra);this.C.element.appendChild(a);this.nu()&&this.load();var c=this.createElement({I:"style"});(g.We("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Ujb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.gs(a,!1);return a},Vjb=function(a,b){b=!b.isCued()&&!g.PG(b,1024);
g.fG(a.B,b);g.fG(a.C,b)},Wjb=function(a,b,c){a.N=!0;
a.G=g.bC(b,c)},Xjb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Xjb(a,e))}return c},akb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.WB(h)&&h.responseXML?h.responseXML:null)&&Yjb(a,h)}};
g.iD()&&(d.onFinish=Zjb(a,d.onFinish));d.postParams={ic_only:"1"};$jb(d,c);a.N=!0;g.bC(b.Va,d)}}},$jb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.XG&&(a.postParams.ic_coll=b.XG);b.RM&&(a.postParams.ic_xml=b.RM);b.SK&&(a.postParams.ic_track=b.SK)},bkb=function(a){var b=new g.U({I:"div"});
g.gs(b.element,!1);var c=new qjb(a.player,b.element,B4(a));g.L(c,b);b.Ea(a.B.element);c.GF();return c},dkb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,ckb(a,b),b.headerText&&a.Wg&&(c=g.jG(b.headerText),a.Wg.setAttribute("title",c))},B4=function(a){if(!a.Z){var b=new Kib(a);
g.L(a,b);var c=new g.$o(a);g.L(a,c);a.Z=new Ljb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.lj)}return a.Z},Yjb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.DF();if(e){var f=g.CF();f&&g.KB(g.Sua)(void 0,e,f,[g.BF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Xjb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=i4(f.type,ekb),p=i4(f.style,fkb),q=$ib(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=fjb;if(null==t)var u=null;else if(g.$a(t)){l=[];for(var x=g.v(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new gjb(m,n,p,u,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=Ujb(f),O=null;switch(l.type){case "branding":if(f.player.U().Vd)break;f.B.element.appendChild(H);O=new z4(H,B4(f),l);break;case "promotion":g.sU(f.player,H,4),O=new Mjb(H,B4(f),l)}O&&O.GF();if(f=O)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=bkb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={jX:l.impression,click:l.click,close:l.close,H_:l.teaser_impression,MK:l.teaser_click},H=f.tracking_params||{},O=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Yo:H.card?g.BF(H.card):null,Gj:H.teaser?g.BF(H.teaser):null,If:H.icon?g.BF(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,EZ:f.image_url,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Yo:H.card?g.BF(H.card):null,Gj:H.teaser?
g.BF(H.teaser):null,If:H.icon?g.BF(H.icon):null,TF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "productListing":f.signin_url&&(O=k4({target:"current",value:f.signin_url}));Q=[];for(var X=f.offers||[],ia=0;ia<X.length;ia++)Q.push(new mjb(g.ze(X[ia].merchant),g.ze(X[ia].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Yo:H.card?g.BF(H.card):null,Gj:H.teaser?g.BF(H.teaser):null,If:H.icon?g.BF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,KC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),rjb:O,qjb:f.signin_title?f.signin_title:void 0,pjb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};t4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Yo:H.card?g.BF(H.card):
null,Gj:H.teaser?g.BF(H.teaser):null,If:H.icon?g.BF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,KC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Yo:H.card?g.BF(H.card):null,Gj:H.teaser?g.BF(H.teaser):null,If:H.icon?g.BF(H.icon):null,TF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},t4(c,e)}}else rjb(a.j,e);c=!0}}c&&
(U3(a.player),a.wJ())},ckb=function(a,b){var c=!1;
a.j||(a.j=bkb(a),g.L(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(sjb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.JT(f)||(c=a.j,d=b.headerText?g.jG(b.headerText):"",g.Af(c.Gb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.BF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.BF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.If=b.icon.infoCardIconRenderer.trackingParams?g.BF(b.icon.infoCardIconRenderer.trackingParams):null,a.wJ());U3(a.player)}},gkb=function(a,b,c,d,e){if(!a.player.U().Vd){var f=[];
b.navigationEndpoint&&g.T(b.navigationEndpoint,g.NU)&&g.T(b.navigationEndpoint,g.NU).browseId&&f.push(new cjb("openUrl","click",new ajb("/channel/"+g.T(b.navigationEndpoint,g.NU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.T(b.subscribeButton,
g.CT)){d.channel_id=g.T(b.subscribeButton,g.CT).channelId;var l;b=g.T(b.subscribeButton,g.CT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.jG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.jG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.jG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.jG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.T(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.L2))?void 0:m.url)||"";l={subscribeText:g.jG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.jG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new gjb(c,"branding","branding",f,d);l=Ujb(a);a.B.element.appendChild(l);f=new z4(l,B4(a),f);f.GF();g.L(f,f);a.K[c]=f}},Zjb=function(a,b){return function(){var c=g.Ka.apply(0,arguments);
a.isDisposed()||a.ma.push(g.tu.Hi(function(){b.apply(null,g.qa(c))}))}},hkb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.kU.prototype.nB=g.ca(29,function(a,b){var c=g.OV(this.zb());c&&c.nB(a,b)});
var W3={},X3=null;g.lb(Z3,g.Vu);g.k=Z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Y3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.oJ();this.Xl("play");this.isPaused()&&this.Xl("resume");this.j=1;var b=g.gb(this);b in W3||(W3[b]=this);Dib();Eib(this,a);return!0};
g.k.stop=function(a){Y3(this);this.j=0;a&&(this.progress=1);Fib(this,this.progress);this.Xl("stop");this.vr()};
g.k.pause=function(){this.isPlaying()&&(Y3(this),this.j=-1,this.Xl("pause"))};
g.k.ya=function(){0==this.j||this.stop(!1);this.Xl("destroy");Z3.Of.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.rL=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new Gib(a,this))};
g.lb(Gib,g.zb);g.lb($3,Z3);$3.prototype.C=function(){};
$3.prototype.rL=function(){this.C();$3.Of.rL.call(this)};
$3.prototype.vr=function(){this.C();$3.Of.vr.call(this)};
$3.prototype.oJ=function(){this.C();$3.Of.oJ.call(this)};
g.lb(Hib,$3);Hib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Kib,g.J);g.k=Kib.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.KC(a,b,c);this.j.push(a);return a};
g.k.MI=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=Bib(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.LC(a);g.Hb(this.j,a)};
g.k.Mf=function(){g.LC(this.j);this.j.length=0};
g.k.ya=function(){this.Mf();g.J.prototype.ya.call(this)};g.w(Nib,g.xV);g.k=Nib.prototype;g.k.load=function(){g.xV.prototype.load.call(this);if(!c4(this)){var a=g.GRa(this.player.getVideoData());a?(a=Mib(a,Oib(this)),d4(this,a,!1)):Pib(this)}};
g.k.unload=function(){d4(this,null);this.C&&(this.C.abort(),this.C=null);g.xV.prototype.unload.call(this)};
g.k.Eh=function(a,b){return c4(this)?"loadCustomEndscreenRenderer"===a?(a=Mib(b,"new"),d4(this,a),!0):null:null};
g.k.getOptions=function(){return c4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ib=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ikb.length;f++){var h=Math.abs(b.width-ikb[f]);if(-1===e||d>=h)e=f,d=h}d=jkb[e];this.B&&g.Vr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.es(e.element,m,f);g.as(e.element,n,p);g.Mu(e.element,kkb);256<m||256<f?g.Ju(e.element,"ytp-ce-large-round"):96<m||96<f?g.Ju(e.element,"ytp-ce-medium-round"):g.Ju(e.element,"ytp-ce-small-round");g.Mu(e.element,lkb);m=h.left+h.width/2;h=h.top+l/2;g.Ju(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mu(e.element,jkb);g.Ju(e.element,d);(e=g.Xe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Vr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())h4(this,this.endscreen.impressionUrls),(a=g.DF())&&this.endscreen.visualElement&&g.RF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ju(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ju(b,"ytp-ce-shown");h4(this,c.impressionUrls);(b=g.DF())&&g.RF(b,c.visualElement);this.player.U().K&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Lu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Lu(b,"ytp-ce-shown");this.player.U().K&&this.player.Qa("endscreenelementhidden",a)}};
g.k.R$=function(a){var b=this;a.target===window&&(new g.Bu(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Mu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ikb=[346,426,470,506,570,640,853,1280,1920],jkb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),lkb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],kkb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var bjb={hsa:"current",iSa:"new"};var djb={CLOSE:"close",IVa:"openUrl",SUBSCRIBE:"subscribe"},ejb={Aqa:"click",CLOSE:"close",CDa:"hidden",W_a:"rollOut",X_a:"rollOver",H1a:"shown"};gjb.prototype.bf=function(){var a=hjb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var fkb={rla:"anchored",U0:"branding",CHANNEL:"channel",Wra:"cta",FDa:"highlightText",GHa:"label",PLAYLIST:"playlist",oYa:"popup",E4a:"speech",SUBSCRIBE:"subscribe",W7a:"title",VIDEO:"video",leb:"website"},ekb={U0:"branding",qoa:"card",nua:"drawer",EDa:"highlight",JNa:"marker",RZa:"promotion",TEXT:"text",Pfb:"widget"};g.w(o4,g.J);g.k=o4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.cK(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.bb.set(a,e);this.context.J.uf([a])};
g.k.GF=function(){this.context.B.subscribe("resize",this.SG,this)};
g.k.Ab=function(){return this.element};
g.k.sL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.rf(this.Ab())};
g.k.SG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=j4(a);if(f){var h=ojb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Nd||!1,n=g.PB(f||"");m&&n&&(n.v||n.list)?e.context.J.Do(n.v,b,n.list,!1):g.iH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A4(this.context.logger,c,l,d);njb(f)||(c=g.DF(),d=b.itct,c&&d&&g.UF(c,g.BF(d)))}};
g.k.ya=function(){this.Ya.clear();this.bb.clear();g.J.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.w(qjb,o4);g.k=qjb.prototype;g.k.ut=function(){this.ra&&t4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.fs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.SG=function(){var a=this.isAvailable();g.gs(this.Ab(),a);g.Nu(this.context.J.getRootNode(),g.XY.IV_DRAWER_ENABLED,a);U3(this.J)};
g.k.destroy=function(){this.J.nB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.JE(this.ma);g.QC(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();o4.prototype.destroy.call(this)};
g.k.T4=function(){if(this.C){A4(this.context.logger,x4(this).Zi.close);var a=g.DF();a&&this.N&&g.UF(a,this.N);s4(this)}};
g.k.p5=function(){g.Nu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.F7=function(){var a=g.DF(),b=x4(this);b=b?b.If:this.If;a&&b&&g.SF(a,[b])};
g.k.E7=function(){var a=g.DF(),b=x4(this);b=b?b.If:this.If;a&&b&&g.TF(a,[b])};
g.k.F1=function(){var a=x4(this);A4(this.context.logger,a.Zi.H_);var b=g.DF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Gj&&c.push(a.Gj);a.If&&c.push(a.If);0<c.length&&g.SF(b,c)}else g.SF(b,[a.Gj,a.If])};
g.k.G7=function(){var a=g.DF(),b=x4(this);a&&b&&g.TF(a,[b.Gj])};
g.k.E1=function(a){var b=x4(this),c=g.DF();this.j?a?(a=this.context.logger,A4(a,b.Zi.MK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gj&&g.UF(c,b.Gj)):(a=this.context.logger,A4(a,b.Zi.MK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.If&&g.UF(c,b.If)):(a=this.context.logger,A4(a,b.Zi.MK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.If&&g.UF(c,this.If))};g.w(y4,o4);y4.prototype.GF=function(){o4.prototype.GF.call(this);Gjb(this)};
y4.prototype.show=function(){o4.prototype.show.call(this);var a=g.DF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.SF(a,[g.BF(b.itct)])};
y4.prototype.hide=function(){o4.prototype.hide.call(this);var a=g.DF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.TF(a,[g.BF(b.itct)])};g.w(z4,y4);z4.prototype.Yw=function(){g.Ju(this.Ab(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.gs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ab().appendChild(b);var c=this.annotation.bf();c&&p4(this,b,c,this.annotation.id,a.session_data);Kjb(this,a)};
z4.prototype.show=function(){if(!this.isActive&&(y4.prototype.show.call(this),this.N||(this.Yw(),this.N=!0),g.gs(this.Ab(),!0),this.isActive=!0,this.B)){try{Hjb(this,this.B)}catch(a){}g.Ju(this.context.J.getRootNode(),"ytp-branding-shown")}};
z4.prototype.hide=function(){this.isActive&&(y4.prototype.hide.call(this),g.gs(this.Ab(),!1),this.isActive=!1,g.Lu(this.context.J.getRootNode(),"ytp-branding-shown"))};
z4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);y4.prototype.destroy.call(this)};g.w(Mjb,y4);g.k=Mjb.prototype;
g.k.Yw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ab().setAttribute("aria-hidden","true");this.Ab().setAttribute("aria-label","Promotion");this.Ab().tabIndex=0;var e=this.annotation.bf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&p4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Kn(f,j4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&p4(this,
this.Ab(),e,this.annotation.id,b.session_data,void 0,c)}g.Ju(this.j,"iv-click-target");e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.Ju(this.j,"iv-click-target"),e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ta(this.B,"click",function(q){Pjb(a,5E3,q)});
c.appendChild(this.B);g.gs(this.B,!1);this.context.j.Ta(this.Ab(),"mouseover",this.C6,this);this.context.j.Ta(this.Ab(),"mouseout",this.B6,this);this.context.j.Ta(this.Ab(),"touchend",function(q){Pjb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.x6:this.w6,this);c.appendChild(this.C);g.Ku(this.Ab(),d);h&&(g.of(this.Ab(),h),n&&h.appendChild(n));g.of(this.Ab(),this.N);g.of(this.Ab(),c)};
g.k.show=function(){this.isActive||(y4.prototype.show.call(this),this.Y||(this.Yw(),this.Y=!0),g.gs(this.Ab(),!0),g.ng(function(){g.Lu(this.Ab(),"iv-promo-inactive")},100,this),this.Ab().removeAttribute("aria-hidden"),this.isActive=!0,Rjb(this),Njb(this),Ojb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ju(this.Ab(),"iv-promo-inactive"),this.isActive=!1,this.Ab().setAttribute("aria-hidden","true"))};
g.k.sL=function(a,b,c,d,e,f){return this.isCollapsed?!1:y4.prototype.sL.call(this,a,b,c,d,e,f)};
g.k.C6=function(a){this.Z=!0;Pjb(this,500,a)};
g.k.B6=function(){this.Z=!1;Qjb(this)};
g.k.w6=function(a){a.stopPropagation();this.hide()};
g.k.x6=function(a){a.stopPropagation();Rjb(this);this.isCollapsed=!0;g.Ju(this.Ab(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();y4.prototype.destroy.call(this)};g.w(Tjb,g.xV);g.k=Tjb.prototype;g.k.Eh=function(a,b){if(!hkb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.r2(b))&&Yjb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(ujb(this.j,b),U3(this.player)),!0}return null};
g.k.getOptions=function(){return hkb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.nu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Nd&&a.ma||g.cU(this.player.app)?!1:1===c&&!b.GU||a.Na.get(b.videoId)||g.KT(b)||g.HRa(b)?!0:!1};
g.k.wJ=function(){if(this.C){var a=this.player.kb().getVideoContentRect(!0);g.es(this.C.element,a.width,a.height);g.as(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Pk();a=this.j;b=b.width;g.Nu(a.D,"iv-drawer-small",426>=b);g.Nu(a.D,"iv-drawer-big",1280<=b)}};
g.k.G1=function(a){Vjb(this,a.state);g.PG(a.state,2)&&(this.Hk()&&this.Xo()&&2!==this.player.getPresentingPlayerType()&&this.oB(!1),this.nB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.WB(h)&&h.responseXML?h.responseXML:null)&&(Yjb(b,h),g.Ju(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.xV.prototype.load.call(this);Vjb(this,this.player.Qb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.iD()&&(a=Zjb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&$jb(e,f);f=f&&(f.RM||f.XG);if(!c.MB||f)c.Va?Wjb(this,c.Va,e):(this.xx=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.JT(h))&&!b.Y&&dkb(b,h)},this.player.addEventListener("videodatachange",this.xx));
g.sU(this.player,this.C.element,4);this.wJ();(f=g.KT(c))&&ckb(this,f);(f=g.HRa(c))&&f.featuredChannel&&gkb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Wg=g.Ze("ytp-cards-button",this.player.getRootNode());g.JT(c)&&dkb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&Wjb(this,b.Va,a)};
g.k.unload=function(){this.player.hf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,U3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.xV.prototype.unload.call(this);this.C.detach();this.xx&&(this.player.removeEventListener("videodatachange",this.xx),this.xx=null)};
g.k.iZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?akb(this):this.load())};
g.k.Hk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.Xo=function(){return!!this.j&&this.j.C};
g.k.oB=function(a,b,c){b=void 0===b?!1:b;this.Hk();this.j&&(a?c?r4(this.j,c,b):r4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):s4(this.j))};
g.k.nB=function(a,b){this.player.qa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.iZ,this);g.Lu(this.player.getRootNode(),g.XY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.tu,c=0,d=a.length;c<d;c++)b.Lj(a[c]);this.ma.length=0;g.xV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.wV("annotations_module",Tjb);g.wV("creatorendscreen",Nib);})(_yt_player);
